import { ServiceCategory, Project, TeamMember, Testimonial, StatItem } from "./types";

export const SERVICES_DATA: ServiceCategory[] = [
  {
    id: "marketing",
    title: "Digital Marketing",
    tagline: "Drive Engagement & Scale Sales",
    description: "Amplify your brand presence across digital channels, ensuring maximum conversion and performance.",
    icon: "Megaphone",
    subItems: [
      {
        name: "Social Media Marketing",
        description: "Engaging monthly content calendars, community management, and consistent visual storytelling across TikTok, Telegram, and LinkedIn.",
      },
      {
        name: "Facebook & Instagram Ads",
        description: "Hyper-targeted meta ad campaigns utilizing precise buyer personas, split A/B testing, and optimized budget strategies to drive conversions.",
      },
      {
        name: "Google Ads Management",
        description: "Search, Display, and Video campaigns designed to put your service in front of people actively searching for it with high intent.",
      },
      {
        name: "Email Marketing",
        description: "Designed newsletter campaigns and automated retention sequences that keep your audience warm and loyal.",
      },
      {
        name: "Influencer Marketing",
        description: "Strategic partnerships with leading Ethiopian creators, digital influencers, and thought leaders to build trusted buzz.",
      },
    ],
  },
  {
    id: "websites",
    title: "Website Development",
    tagline: "High-Performance Pixel-Perfect Arenas",
    description: "Craft modern, lightning-fast digital storefronts and profiles that load instantly even on low-bandwidth networks.",
    icon: "Code",
    subItems: [
      {
        name: "Company Profile Websites",
        description: "Stunning corporate showcase sites custom designed to present services, portfolios, and capture qualified incoming leads.",
      },
      {
        name: "E-commerce Websites",
        description: "Completely secure, user-friendly e-commerce systems with integrated local payment gateways and rich inventory controls.",
      },
      {
        name: "Landing Pages",
        description: "Conversion-optimized, highly focused single pages designed to turn ad traffic into direct WhatsApp or form inquiries.",
      },
      {
        name: "Portfolio Websites",
        description: "Artistic yet professional visual showcases tailored for artists, agencies, architects, and high-end consultancies.",
      },
      {
        name: "Website Maintenance",
        description: "Incredible hosting upkeep, database optimization, routine security monitoring, and content updates.",
      },
    ],
  },
  {
    id: "branding",
    title: "Branding & Design",
    tagline: "Stand Out In Cluttered Markets",
    description: "We shape unique identities that communicate professionalism, creative depth, and absolute market authority.",
    icon: "Palette",
    subItems: [
      {
        name: "Logo Design",
        description: "Hand-drawn vector logos that condense complex commercial missions into timeless, memorable symbols.",
      },
      {
        name: "Brand Identity Design",
        description: "Comprehensive design systems complete with typography systems, strict color schemes, and usage guidelines.",
      },
      {
        name: "Marketing Materials",
        description: "Beautifully designed digital flyers, company profiles, brochures, uniforms, and exhibition rollups.",
      },
      {
        name: "UI/UX Design",
        description: "In-depth visual research, low-fidelity wireframes, and gorgeous Figma interaction prototypes built with meticulous care.",
      },
    ],
  },
  {
    id: "content",
    title: "Content Creation",
    tagline: "Authentic Storytelling That Connects",
    description: "Produce high-fidelity visual and written content that keeps audiences returning and sharing.",
    icon: "Camera",
    subItems: [
      {
        name: "Social Media Content",
        description: "Custom high-quality graphics, visual cards, viral reels, and informative micro-infographics optimized for local platforms.",
      },
      {
        name: "Video Production",
        description: "Cinematic promotional commercials, interview formats, office tours, and instructional Reels/TikTok items.",
      },
      {
        name: "Photography",
        description: "High-definition product photography, atmospheric corporate team headshots, and event highlight galleries.",
      },
      {
        name: "Copywriting",
        description: "Persuasive and engaging copy written in English and Amharic to speak perfectly to local sentiments.",
      },
    ],
  },
  {
    id: "seo",
    title: "SEO Services",
    tagline: "Own the First Organic Page",
    description: "Structure and optimize your platform to rank highly on search engines, driving perpetual free traffic.",
    icon: "Search",
    subItems: [
      {
        name: "On-Page SEO",
        description: "Deep content structures, keyword-enriched content placement, and meta tag optimizations.",
      },
      {
        name: "Technical SEO",
        description: "Speed audits, clean sitemaps, structured schema data, crawler accessibility, and mobile-responsiveness enhancements.",
      },
      {
        name: "Local SEO",
        description: "Complete Google Business Profile setup, local citations, and reviews strategy to dominate Addis Ababa map rankings.",
      },
      {
        name: "SEO Audits",
        description: "Granular competitor reports, drop-off analysis, keyword opportunity identification, and action roadmaps.",
      },
    ],
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: "proj1",
    title: "Zemen Luxury Real Estate Portfolio",
    category: "websites",
    categoryLabel: "Website Development",
    client: "Zemen Homes",
    year: "2024",
    description: "A gorgeous, high-end company profile and properties catalogue with virtual tour integration, structured specifically to make property exploration smooth even on mobile networks.",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=600&auto=format&fit=crop",
    results: "+240% qualified property leads via custom inquiry pathways in the first 3 months",
    duration: "6 Weeks",
    technologies: ["React", "Tailwind CSS", "Framer Motion", "Vite"],
  },
  {
    id: "proj2",
    title: "Sheger Apparel Premium E-Commerce",
    category: "websites",
    categoryLabel: "Website Development & Marketing",
    client: "Sheger Apparels",
    year: "2024",
    description: "We built a fully customized, rapid-loading e-commerce platform integrated with local payment providers like Chapa and Telebirr. To drive immediate traffic, we launched hyper-targeted social ad campaigns.",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=600&auto=format&fit=crop",
    results: "200% online sales increase within six months & 30k+ active web visitors monthly",
    duration: "8 Weeks",
    technologies: ["React", "Express", "Tailwind", "Chapa API", "Paid Meta Ads"],
  },
  {
    id: "proj3",
    title: "Abyssinia Academy Brand Identity",
    category: "branding",
    categoryLabel: "Branding & Design",
    client: "Abyssinia Academy",
    year: "2023",
    description: "A complete overhaul of Abyssinia's brand footprint. We designed a timeless logo, developed custom corporate document templates, and compiled a comprehensive brand styling guide for print and digital assets.",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop",
    results: "Highly unified visual tone across 4 campuses and +35% surge in student enrollments",
    duration: "4 Weeks",
    technologies: ["Figma", "Adobe Illustrator", "Brand Design", "Print Strategy"],
  },
  {
    id: "proj4",
    title: "EcoGreen Ethiopia NGO Awareness Drive",
    category: "marketing",
    categoryLabel: "Digital Marketing & Content",
    client: "EcoGreen Africa Advocacy",
    year: "2024",
    description: "We designed a multi-channel educational outreach campaign across Telegram and TikTok with custom-produced Amharic infovideos and local advocate networking.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    results: "Reached 1.2M users organically with over 20,000 petition signs recorded",
    duration: "12 Weeks",
    technologies: ["Videography", "Telegram Marketing", "Copywriting", "Influencer Collabs"],
  },
  {
    id: "proj5",
    title: "Selam General Hospital SEO Audit & Rank Campaign",
    category: "seo",
    categoryLabel: "SEO Services",
    client: "Selam Hospital",
    year: "2024",
    description: "Diagnosed page core web vitals and optimized the hierarchy. Focused heavily on geographic maps search optimization, listing standard healthcare keywords in both English and Amharic queries.",
    imageUrl: "https://images.unsplash.com/photo-1538108176447-280586497d96?q=80&w=600&auto=format&fit=crop",
    results: "Moved medical keywords from Page 5 to Rank #2 globally in Addis Ababa",
    duration: "10 Weeks",
    technologies: ["Technical SEO", "Ahrefs", "Google My Business", "On-Page Dev"],
  },
  {
    id: "proj6",
    title: "Habesha Roast Social Media Launch",
    category: "creation",
    categoryLabel: "Content Creation",
    client: "Habesha Coffee Roasters",
    year: "2024",
    description: "Created high-end product photography and social media templates displaying the coffee roaster’s authentic traditional processes blended with modern coffee culture.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=600&auto=format&fit=crop",
    results: "+15k highly engaged Instagram & Telegram followers in less than two months",
    duration: "5 Weeks",
    technologies: ["Figma", "Studio Photography", "Video Reels", "Graphic Layouts"],
  },
];

export const TEAM_DATA: TeamMember[] = [
  {
    id: "team1",
    name: "Yohannes Siltawi",
    role: "CEO & Founder",
    department: "Executive Strategy",
    bio: "Strategist with over 7 years in digital consulting across East Africa, guiding brand directions to maximum ROI.",
    experience: "7+ Years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "team2",
    name: "Semhal Belay",
    role: "Digital Marketing Manager",
    department: "Marketing Strategy",
    bio: "Passionate about consumer psychology and ROI. Coordinates social strategy, influencer ties, and large account operations.",
    experience: "5+ Years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "team3",
    name: "Fitsum Takele",
    role: "Lead Web Developer",
    department: "Web Engineering",
    bio: "Specializes in blazing-fast React and hybrid web architectures. Ensures perfect responsiveness on both 4G mobile and desktop.",
    experience: "6+ Years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "team4",
    name: "Tigist Demissie",
    role: "Senior Graphic Designer",
    department: "Branding & UI/UX",
    bio: "Weaves Ethiopian heritage motives into minimalist contemporary aesthetics. Figma lover and vector maestro.",
    experience: "4+ Years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "team5",
    name: "Bruh Melaku",
    role: "Creative Director",
    department: "Content Creation",
    bio: "Award-winning content creator, director, and photographer. Delivers cinematic commercials that tell deeply touching brand tales.",
    experience: "5+ Years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "team6",
    name: "Eden Birhane",
    role: "Senior SEO Specialist",
    department: "Search Optimization",
    bio: "Expert on crawling mechanisms and search index logic. Dedicated to bringing local Ethiopian brands onto Google's global front seat.",
    experience: "4+ years",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "test1",
    quote: "Siltawi helped us increase our online sales by 200% within six months. Their performance ads on Instagram changed the trajectory of our retail stream entirely.",
    author: "Elsa Tadesse",
    role: "Director of Retail Growth",
    company: "Sheger Apparels",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "test2",
    quote: "Their incredible website design and dedicated marketing services completely transformed our brand presence. The web page loads instantly even under high density traffic.",
    author: "Dawit Zemen",
    role: "Founder & Architect",
    company: "Zemen Living Spaces",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "test3",
    quote: "We were struggling to be found by clients in Addis Ababa. Siltawi carried out a complete local SEO optimization and now we are the Top-3 highlighted medical institution.",
    author: "Dr. Henok Seyoum",
    role: "Medical Services Administrator",
    company: "Selam General Hospital",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop",
  },
];

export const STATS_DATA: StatItem[] = [
  {
    id: "stat1",
    label: "Projects Completed",
    value: 100,
    suffix: "+",
    description: "across start-ups, corporations, and NGOs in the region.",
  },
  {
    id: "stat2",
    label: "Active Clients",
    value: 50,
    suffix: "+",
    description: "trusting us month after month to manage their footprint.",
  },
  {
    id: "stat3",
    label: "Team Members",
    value: 15,
    suffix: "",
    description: "dedicated creative directors, branding gurus, and engineers.",
  },
  {
    id: "stat4",
    label: "Client Satisfaction",
    value: 95,
    suffix: "%",
    description: "average customer retention and net rating scores.",
  },
];
